<a href="https://colab.research.google.com/github/sumitsethy/EVA/blob/master/filefromcolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import keras


Using TensorFlow backend.


In [0]:
from keras_preprocessing import image

In [0]:
image

<module 'keras_preprocessing.image' from '/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/__init__.py'>

In [0]:
from keras.datasets import mnist

In [0]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [0]:
X_train.shape

(60000, 28, 28)

In [0]:
X_train.ndim

3

In [0]:
X_train = X_train.reshape(X_train.shape[0], 28, 28,1)

In [0]:
X_train.shape, X_train.ndim

((60000, 28, 28, 1), 4)

In [0]:
X_train.dtype

dtype('uint8')

In [0]:
X_train = X_train.astype('float32')

In [0]:
X_train.dtype

dtype('float32')

In [0]:
print(X_train[0][6])

[[  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 30]
 [ 36]
 [ 94]
 [154]
 [170]
 [253]
 [253]
 [253]
 [253]
 [253]
 [225]
 [172]
 [253]
 [242]
 [195]
 [ 64]
 [  0]
 [  0]
 [  0]
 [  0]]


In [0]:
X_train /= 255

In [0]:
X_train[0][6]

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.11764706],
       [0.14117648],
       [0.36862746],
       [0.6039216 ],
       [0.6666667 ],
       [0.99215686],
       [0.99215686],
       [0.99215686],
       [0.99215686],
       [0.99215686],
       [0.88235295],
       [0.6745098 ],
       [0.99215686],
       [0.9490196 ],
       [0.7647059 ],
       [0.2509804 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ]], dtype=float32)

In [0]:
from keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(featurewise_center=True, featurewise_std_normalization=True)
datagen.fit(X_train)

In [0]:
datagen.mean, datagen.std

(array([[[0.13066062]]], dtype=float32),
 array([[[0.30810776]]], dtype=float32))

In [0]:
if self.featurewise_center:
            self.mean = np.mean(x, axis=(0, self.row_axis, self.col_axis))
            broadcast_shape = [1, 1, 1]
            broadcast_shape[self.channel_axis - 1] = x.shape[self.channel_axis]
            self.mean = np.reshape(self.mean, broadcast_shape)
            x -= self.mean

if self.featurewise_std_normalization:
    self.std = np.std(x, axis=(0, self.row_axis, self.col_axis))
    broadcast_shape = [1, 1, 1]
    broadcast_shape[self.channel_axis - 1] = x.shape[self.channel_axis]
    self.std = np.reshape(self.std, broadcast_shape)
    x /= (self.std + 1e-6)

In [0]:
my_mean = np.mean(X_train, axis=(0, datagen.row_axis, datagen.col_axis))
print(my_mean)
print(my_mean.shape)

broadcast_shape = [1, 1, 1]
broadcast_shape[datagen.channel_axis - 1] = X_train.shape[datagen.channel_axis]
print(broadcast_shape)

my_mean = np.reshape(my_mean, broadcast_shape)
print(my_mean)
print(my_mean.shape)

#x -= self.mean

[0.13066062]
(1,)
[1, 1, 1]
[[[0.13066062]]]
(1, 1, 1)


In [0]:
X_train[0][6] - my_mean

array([[[-0.13066062],
        [-0.13066062],
        [-0.13066062],
        [-0.13066062],
        [-0.13066062],
        [-0.13066062],
        [-0.13066062],
        [-0.13066062],
        [-0.01301356],
        [ 0.01051585],
        [ 0.23796684],
        [ 0.47326097],
        [ 0.5360061 ],
        [ 0.8614962 ],
        [ 0.8614962 ],
        [ 0.8614962 ],
        [ 0.8614962 ],
        [ 0.8614962 ],
        [ 0.7516923 ],
        [ 0.54384923],
        [ 0.8614962 ],
        [ 0.818359  ],
        [ 0.63404524],
        [ 0.12031978],
        [-0.13066062],
        [-0.13066062],
        [-0.13066062],
        [-0.13066062]]], dtype=float32)

In [0]:
broadcast_shape = [1, 1, 1]
broadcast_shape[datagen.channel_axis - 1] = X_train.shape[datagen.channel_axis]
broadcast_shape

[1, 1, 1]

In [0]:
datagen.row_axis, datagen.col_axis, datagen.channel_axis

(1, 2, 3)

In [0]:
np.mean(X_train.flatten())

0.13066062

In [0]:
np.mean(X_train, axis=(0, 1, 2))
# If this is a tuple of ints, a mean is performed over multiple axes


array([0.13066062], dtype=float32)

In [0]:
np.mean(np.mean(X_train[0], axis=0), np.mean(X_train[0], axis=1), np.mean(X_train[0], axis=2))

TypeError: ignored

In [0]:
np.mean(X_train)

0.13066062

In [0]:
print(np.mean(X_train[0]))
print(np.mean(X_train[0], axis=0))
print(np.mean(X_train[0], axis=1))
print(np.mean(X_train[0], axis=2))

0.13768007
[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.0267507 ]
 [0.05952381]
 [0.06960785]
 [0.10420168]
 [0.17843139]
 [0.19873951]
 [0.22170869]
 [0.2936975 ]
 [0.35882354]
 [0.3777311 ]
 [0.30476192]
 [0.30308124]
 [0.33599442]
 [0.3666667 ]
 [0.24579833]
 [0.15854342]
 [0.07941177]
 [0.07745098]
 [0.06736695]
 [0.0267507 ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.18417367]
 [0.40616247]
 [0.40812325]
 [0.33193278]
 [0.1767507 ]
 [0.07170868]
 [0.08179271]
 [0.07338936]
 [0.10784314]
 [0.1359944 ]
 [0.12801121]
 [0.11218487]
 [0.11414565]
 [0.15042017]
 [0.22507003]
 [0.23109244]
 [0.22338936]
 [0.23865546]
 [0.2595238 ]
 [0.19467786]
 [0.        ]
 [0.        ]
 [0.        ]]
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        

In [0]:
print(np.mean(X_train[0]).shape)
print(np.mean(X_train[0], axis=0).shape)
print(np.mean(X_train[0], axis=1).shape)
print(np.mean(X_train[0], axis=2).shape)

()
(28, 1)
(28, 1)
(28, 28)


#### Concept Testing 

In [0]:
a = np.array([[1, 2], [3, 4]])
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))
print(np.mean(a, axis=2)) # as there is no depth/channel

2.5
[2. 3.]
[1.5 3.5]


IndexError: ignored

### Date operations

In [0]:
import pandas as pd

In [0]:
test = pd.Series(pd.date_range('2000', freq='D', periods=10))

0   2000-01-01
1   2000-01-02
2   2000-01-03
3   2000-01-04
4   2000-01-05
5   2000-01-06
6   2000-01-07
7   2000-01-08
8   2000-01-09
9   2000-01-10
dtype: datetime64[ns]